name: Cleanup Untagged Images

on:
  schedule:
    - cron: '0 0 * * 0,3'
  workflow_dispatch:

env:
  PACKAGE_NAME: kube-sentinel
  DAYS_OLD: 7

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup untagged images
        uses: snok/container-retention-policy@v3
        with:
          account-type: ${{ github.event.repository.owner.type == 'Organization' && 'org' || 'personal' }}
          image-names: ${{ env.PACKAGE_NAME }}
          cut-off: ${{ env.DAYS_OLD }} days ago UTC
          untagged-only: true
          token: ${{ secrets.GITHUB_TOKEN }}

